sedecdi/web-gestion/src/main/java/es/imserso/sede/web/gestion/view/IdiomaBean.java
package es.imserso.sede.web.gestion.view;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.ejb.SessionContext;
import javax.ejb.Stateful;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import es.imserso.sede.model.Idioma;

/**
 * Backing bean for Idioma entities.
 * <p/>
 * This class provides CRUD functionality for all Idioma entities. It focuses
 * purely on Java EE 6 standards (e.g. <tt>&#64;ConversationScoped</tt> for
 * state management, <tt>PersistenceContext</tt> for persistence,
 * <tt>CriteriaBuilder</tt> for searches) rather than introducing a CRUD
 * framework or custom base class.
 */

@Named
@Stateful
@ConversationScoped
public class IdiomaBean implements Serializable {

	private static final long serialVersionUID = 1L;

	/*
	 * Support creating and retrieving Idioma entities
	 */

	private Long id;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	private Idioma idioma;

	public Idioma getIdioma() {
		return this.idioma;
	}

	public void setIdioma(Idioma idioma) {
		this.idioma = idioma;
	}

	@Inject
	private Conversation conversation;

	@PersistenceContext(unitName = "primary", type = PersistenceContextType.EXTENDED)
	private EntityManager entityManager;

	public String create() {
		if (this.conversation.isTransient()) {
			this.conversation.begin();
			this.conversation.setTimeout(1800000L);
		}
		return "create?faces-redirect=true";
	}

	public void retrieve() {

		if (FacesContext.getCurrentInstance().isPostback()) {
			return;
		}

		if (this.conversation.isTransient()) {
			this.conversation.begin();
			this.conversation.setTimeout(1800000L);
		}

		if (this.id == null) {
			this.example = new Idioma();
			this.idioma = this.example;
		} else {
			this.idioma = findById(getId());
		}
	}

	public Idioma findById(Long id) {

		return this.entityManager.find(Idioma.class, id);
	}

	/*
	 * Support updating and deleting Idioma entities
	 */

	public String update() {
		this.conversation.end();

		try {
			if (this.id == null) {
				this.entityManager.persist(this.idioma);
				this.entityManager.flush();
				return "search?faces-redirect=true";
			} else {
				this.entityManager.merge(this.idioma);
				this.entityManager.flush();
				return "view?faces-redirect=true&id=" + this.idioma.getId();
			}
		} catch (Exception e) {
			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(e.getMessage()));
			return null;
		}
	}

	public String delete() {
		this.conversation.end();

		try {
			Idioma deletableEntity = findById(getId());

			this.entityManager.remove(deletableEntity);
			this.entityManager.flush();
			return "search?faces-redirect=true";
		} catch (Exception e) {
			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(e.getMessage()));
			return null;
		}
	}

	

	  
	/*
	 * Support searching Idioma entities with pagination
	 */

	private int page;
	private long count;
	private List<Idioma> pageItems;

	private Idioma example = new Idioma();

	public int getPage() {
		return this.page;
	}

	public void setPage(int page) {
		this.page = page;
	}

	public int getPageSize() {
		return 10;
	}

	public Idioma getExample() {
		return this.example;
	}

	public void setExample(Idioma example) {
		this.example = example;
	}

	public String search() {
		this.page = 0;
		return null;
	}

	public void paginate() {

		CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();

		// Populate this.count

		CriteriaQuery<Long> countCriteria = builder.createQuery(Long.class);
		Root<Idioma> root = countCriteria.from(Idioma.class);
		countCriteria = countCriteria.select(builder.count(root)).where(
				getSearchPredicates(root));
		this.count = this.entityManager.createQuery(countCriteria)
				.getSingleResult();

		// Populate this.pageItems

		CriteriaQuery<Idioma> criteria = builder.createQuery(Idioma.class);
		root = criteria.from(Idioma.class);
		TypedQuery<Idioma> query = this.entityManager.createQuery(criteria
				.select(root).where(getSearchPredicates(root)));
		query.setFirstResult(this.page * getPageSize()).setMaxResults(
				getPageSize());
		this.pageItems = query.getResultList();
	}

	private Predicate[] getSearchPredicates(Root<Idioma> root) {

		CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();
		List<Predicate> predicatesList = new ArrayList<Predicate>();

		String locale = this.example.getLocale();
		if (locale != null && !"".equals(locale)) {
			predicatesList.add(builder.like(
					builder.lower(root.<String> get("locale")),
					'%' + locale.toLowerCase() + '%'));
		}
		String nombre = this.example.getNombre();
		if (nombre != null && !"".equals(nombre)) {
			predicatesList.add(builder.like(
					builder.lower(root.<String> get("nombre")),
					'%' + nombre.toLowerCase() + '%'));
		}

		return predicatesList.toArray(new Predicate[predicatesList.size()]);
	}

	public List<Idioma> getPageItems() {
		return this.pageItems;
	}

	public long getCount() {
		return this.count;
	}

	/*
	 * Support listing and POSTing back Idioma entities (e.g. from inside an
	 * HtmlSelectOneMenu)
	 */

	public List<Idioma> getAll() {

		CriteriaQuery<Idioma> criteria = this.entityManager
				.getCriteriaBuilder().createQuery(Idioma.class);
		return this.entityManager.createQuery(
				criteria.select(criteria.from(Idioma.class))).getResultList();
	}

	@Resource
	private SessionContext sessionContext;

	public Converter getConverter() {

		final IdiomaBean ejbProxy = this.sessionContext
				.getBusinessObject(IdiomaBean.class);

		return new Converter() {

			@Override
			public Object getAsObject(FacesContext context,
					UIComponent component, String value) {

				return ejbProxy.findById(Long.valueOf(value));
			}

			@Override
			public String getAsString(FacesContext context,
					UIComponent component, Object value) {

				if (value == null) {
					return "";
				}

				return String.valueOf(((Idioma) value).getId());
			}
		};
	}

	/*
	 * Support adding children to bidirectional, one-to-many tables
	 */

	private Idioma add = new Idioma();

	public Idioma getAdd() {
		return this.add;
	}

	public Idioma getAdded() {
		Idioma added = this.add;
		this.add = new Idioma();
		return added;
	}
}

sedecdi/web-gestion/src/main/webapp/resources/scaffold/pageTemplate.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<h:head>
	<title>#{empty pageTitle ? 'Page Title' : pageTitle}</title>
	<link rel="icon" href='#{resource["favicon.ico"]}' />
	<h:outputStylesheet name="bootstrap.css" />
	<h:outputStylesheet name="forge-style.css" />
</h:head>

<h:body>
	<ui:debug rendered="#{facesContext.application.projectStage == 'Development'}" />
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<h:link id="brandLink" outcome="/index.xhtml" styleClass="brand">
					<h:outputText value="Welcome to " rendered=" #{request.userPrincipal !=null} "/>
                    Scaffold
                    <h:outputText value=",  #{request.userPrincipal.name}" rendered="#{request.userPrincipal !=null} "/>
				</h:link>
				<div class="nav-collapse collapse">
					<ul class="nav">
						<li><a href="http://forge.jboss.org/document/hands-on-lab">How to Customize</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<div class="container forgecontainer">
		<div id="navigation">
			<h:link id="homeLink" outcome="/index.xhtml">
				<h:graphicImage value='#{resource["forge-logo.png"]}' alt="Forge... get hammered" border="0" />	
			</h:link>
			<ul>
				<li>
					<h:link outcome="/admin/historicoEstadoSolicitud/search" value="Historico Estado Solicitud"/>
				</li>
				<li>
					<h:link outcome="/admin/idioma/search" value="Idioma"/>
				</li>
				<li>
					<h:link outcome="/admin/plantillaEmail/search" value="Plantilla Email"/>
				</li>
				<li>
					<h:link outcome="/admin/plantillaPdf/search" value="Plantilla Pdf"/>
				</li>
				<li>
					<h:link outcome="/admin/justificantePdf/search" value="Justificante Pdf"/>
				</li>
				<li>
					<h:link outcome="/admin/solicitud/search" value="Solicitud"/>
				</li>
				<li>
					<h:link outcome="/admin/solicitudPdf/search" value="Solicitud Pdf"/>
				</li>
				<li>
					<h:link outcome="/admin/tramite/search" value="Tramite"/>
				</li>
				<li>
					<h:link outcome="/admin/usuario/search" value="Usuario"/>
				</li>
			</ul>
		</div>

		<div id="content">
			<h1>
				<ui:insert name="header" />
			</h1>
			<h2>
				<ui:insert name="subheader" />
			</h2>

			<ui:insert name="main" />
		</div>
	</div>

	<footer>
		<div id="footer-wrapper">
	    	<p>Powered by <a href="http://jboss.org/forge">Forge</a></p>
	    </div>
	</footer>

</h:body>
</html>

sedecdi/web-gestion/src/main/webapp/resources/scaffold/paginator.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	
	<h:panelGroup styleClass="paginator" rendered="#{paginatorBean.count gt paginatorBean.pageSize}">
		<!-- Use commandLink, not outputLink, so that search criteria is not lost -->
		<h:commandLink styleClass="btn btn-primary" rendered="#{paginatorBean.page gt 0}">
			<f:param name="page" value="#{paginatorBean.page - 1}"/>
			&lt; Previous 
		</h:commandLink>
		<h:outputText styleClass="paginator-content" value="#{paginatorBean.page * paginatorBean.pageSize + 1} to #{paginatorBean.page * paginatorBean.pageSize + fn:length(paginatorBean.pageItems)} (of #{paginatorBean.count})"/>
		<h:commandLink styleClass="btn btn-primary" rendered="#{(paginatorBean.page + 1) * paginatorBean.pageSize lt paginatorBean.count}">
			<f:param name="page" value="#{paginatorBean.page + 1}"/>
			Next &gt;
		</h:commandLink>
	</h:panelGroup>

</ui:composition>